services:
  fxflow:
    build: .
    container_name: fxflow-cookie
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    deploy:
      resources:
        limits:
          memory: 1g
